services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  app:
    build:
      context: app
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - ./app:/app
    ports:
      - 8523:8000
    command: ["fastapi", "dev", "--host", "0.0.0.0", "app/main.py"]

  client:
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./client:/client

  pgwarehouse:
    build:
      context: pgwarehouse
      dockerfile: Dockerfile
    volumes:
      - ./pgwarehouse:/pgwarehosue
    environment:
      PGHOST: postgres
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      SNOWSQL_ACCOUNT: ${SNOWSQL_ACCOUNT}
      SNOWSQL_DATABASE: ${SNOWSQL_DATABASE}
      SNOWSQL_SCHEMA: ${SNOWSQL_SCHEMA}
      SNOWSQL_WAREHOUSE: ${SNOWSQL_WAREHOUSE}
      SNOWSQL_USER: ${SNOWSQL_USER}
      SNOWSQL_ROLE: ${SNOWSQL_ROLE}
      SNOWSQL_PWD: ${SNOWSQL_PWD}
