services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  app:
    build:
      context: app
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - ./app:/app
    ports:
      - 8523:8000
    command: ["fastapi", "dev", "--host", "0.0.0.0", "app/main.py"]

  client:
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./client:/client

  pgwarehouse:
    build:
      context: pgwarehouse
      dockerfile: Dockerfile
    volumes:
      - ./pgwarehouse:/pgwarehosue
    environment:
      PGHOST: postgres
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      SNOWSQL_ACCOUNT: ${SNOWSQL_ACCOUNT}
      SNOWSQL_DATABASE: ${SNOWSQL_DATABASE}
      SNOWSQL_SCHEMA: ${SNOWSQL_SCHEMA}
      SNOWSQL_WAREHOUSE: ${SNOWSQL_WAREHOUSE}
      SNOWSQL_USER: ${SNOWSQL_USER}
      SNOWSQL_ROLE: ${SNOWSQL_ROLE}
      SNOWSQL_PWD: ${SNOWSQL_PWD}

  snowflake_container:
    build:
      context: snowflake_container
      dockerfile: Dockerfile
    working_dir: /snowflake_container/app
    environment:
      SNOWSQL_ACCOUNT: ${SNOWSQL_ACCOUNT}
      SNOWSQL_DATABASE: ${SNOWSQL_DATABASE}
      SNOWSQL_SCHEMA: ${SNOWSQL_SCHEMA}
      SNOWSQL_WAREHOUSE: ${SNOWSQL_WAREHOUSE}
      SNOWSQL_USER: ${SNOWSQL_USER}
      SNOWSQL_ROLE: ${SNOWSQL_ROLE}
      SNOWSQL_PWD: ${SNOWSQL_PWD}
    volumes:
      - ./snowflake_container:/snowflake_container
    ports:
      - 8524:5000
    command: ["flask", "--app", "snowy", "run", "--host", "0.0.0.0"]

  snow_containers_streamlit:
    build:
      context: snow_containers_streamlit
      dockerfile: Dockerfile
    working_dir: /snow_containers_streamlit
    volumes:
      - ./snow_containers_streamlit:/snow_containers_streamlit
    environment:
      SNOWSQL_ACCOUNT: ${SNOWSQL_ACCOUNT}
      SNOWSQL_DATABASE: ${SNOWSQL_DATABASE}
      SNOWSQL_SCHEMA: ${SNOWSQL_SCHEMA}
      SNOWSQL_WAREHOUSE: ${SNOWSQL_WAREHOUSE}
      SNOWSQL_USER: ${SNOWSQL_USER}
      SNOWSQL_ROLE: ${SNOWSQL_ROLE}
      SNOWSQL_PWD: ${SNOWSQL_PWD}
      SNOW_SANDBOX_ROLE: ${SNOW_SANDBOX_ROLE}
    ports:
      - 8525:8501

    command: ["streamlit", "run", "app.py"]

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8526:80